# Generated by Django 4.0 on 2021-12-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_parent',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
