# Generated by Django 4.0 on 2021-12-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_cartproduct_cart_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='unique_data',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
