# Generated by Django 4.0 on 2021-12-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_cartproduct_unique_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='specification_name',
            field=models.CharField(max_length=255),
        ),
    ]
