# Generated by Django 4.0 on 2021-12-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_remove_product_cart_product_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProductNew',
            new_name='CartProduct',
        ),
        migrations.RenameModel(
            old_name='ProductNew',
            new_name='Product',
        ),
    ]
