# Generated by Django 4.0 on 2021-12-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_productspecification_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_specification',
        ),
        migrations.AddField(
            model_name='product',
            name='product_specification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_specifications', to='mainapp.productspecification'),
            preserve_default=False,
        ),
    ]
