# Generated by Django 4.0 on 2021-12-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_product_product_specification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
    ]
